<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('users')->insert([
            ['id' => 1, 'name' => 'Alice', 'email' => 'alice@example.com', 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            ['id' => 2, 'name' => 'Bob',   'email' => 'bob@example.com',   'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
        ]);

        DB::table('categories')->insert([
            ['id' => 1, 'name' => 'Technology', 'slug' => 'technology', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 2, 'name' => 'Politics',   'slug' => 'politics',   'created_at' => now(), 'updated_at' => now()],
            ['id' => 3, 'name' => 'Sports',     'slug' => 'sports',     'created_at' => now(), 'updated_at' => now()],
            ['id' => 4, 'name' => 'Health',     'slug' => 'health',     'created_at' => now(), 'updated_at' => now()],
            ['id' => 5, 'name' => 'Business',   'slug' => 'business',   'created_at' => now(), 'updated_at' => now()],
            ['id' => 6, 'name' => 'World',      'slug' => 'world',      'created_at' => now(), 'updated_at' => now()],
        ]);

        DB::table('tags')->insert([
            ['id' => 1,  'name' => 'AI',           'slug' => 'ai',           'created_at' => now(), 'updated_at' => now()],
            ['id' => 2,  'name' => 'Startup',      'slug' => 'startup',      'created_at' => now(), 'updated_at' => now()],
            ['id' => 3,  'name' => 'Mobile',       'slug' => 'mobile',       'created_at' => now(), 'updated_at' => now()],
            ['id' => 4,  'name' => 'Economy',      'slug' => 'economy',      'created_at' => now(), 'updated_at' => now()],
            ['id' => 5,  'name' => 'Election',     'slug' => 'election',     'created_at' => now(), 'updated_at' => now()],
            ['id' => 6,  'name' => 'Football',     'slug' => 'football',     'created_at' => now(), 'updated_at' => now()],
            ['id' => 7,  'name' => 'Nutrition',    'slug' => 'nutrition',    'created_at' => now(), 'updated_at' => now()],
            ['id' => 8,  'name' => 'Finance',      'slug' => 'finance',      'created_at' => now(), 'updated_at' => now()],
            ['id' => 9,  'name' => 'Climate',      'slug' => 'climate',      'created_at' => now(), 'updated_at' => now()],
            ['id' => 10, 'name' => 'Cybersecurity','slug' => 'cybersecurity','created_at' => now(), 'updated_at' => now()],
        ]);

        $articles = [
            [
                'id'           => 1,
                'title'        => 'AI Revolution Reshapes the Tech Industry',
                'slug'         => 'ai-revolution-reshapes-tech-industry',
                'excerpt'      => 'How artificial intelligence is fundamentally changing how software is built.',
                'content'      => "Artificial intelligence is no longer a futuristic concept confined to research labs and science fiction. Today, AI is embedded in almost every layer of the technology stack — from code assistants that help developers write better software, to recommendation engines that surface the right content at the right time.\n\nMajor tech giants including Google, Microsoft, and Meta have dramatically shifted their product roadmaps to put AI at the center. Microsoft's deep integration of OpenAI models into Azure, Office 365, and GitHub Copilot has set a new benchmark for how productivity tools should work. Meanwhile, startups are emerging at an unprecedented rate, each trying to carve out a niche in an AI-first world.\n\nFor developers, the change is particularly profound. Tools like GitHub Copilot, Cursor, and Amazon CodeWhisperer can now generate entire functions, write unit tests, and even suggest architectural patterns based on natural language prompts. While some fear this will reduce the need for human programmers, most experts argue it simply raises the bar — shifting focus from syntax to system design.\n\nIn Indonesia, the AI wave is also being felt. Several local startups have begun integrating large language models into their products, targeting industries such as legal tech, agri-tech, and healthcare. Government initiatives like the National AI Strategy aim to position Indonesia as a regional leader in AI adoption by 2030, with significant investment in talent development and digital infrastructure.",
                'image_url'    => 'https://picsum.photos/seed/ai/800/400',
                'category_id'  => 1,
                'author'       => 'Jane Smith',
                'views'        => 5420,
                'published_at' => '2026-04-28 08:00:00',
            ],
            [
                'id'           => 2,
                'title'        => 'New Startup Raises $50M in Series B Funding',
                'slug'         => 'new-startup-raises-50m-series-b',
                'excerpt'      => 'A local startup disrupts logistics with drone delivery.',
                'content'      => "A Jakarta-based logistics startup has secured \$50 million in Series B funding, marking one of the largest rounds for an Indonesian tech company this year. The round was led by a Southeast Asian venture capital firm, with participation from two existing investors.\n\nThe startup, which operates a drone-based last-mile delivery network, plans to use the funds to expand its operations from Java to Sumatra and Kalimantan. The company currently handles over 10,000 deliveries per day across 12 cities, with an average delivery time of under 30 minutes.\n\n\"We believe drone logistics is the future of urban delivery in Indonesia,\" said the company's CEO. \"The archipelago geography that makes traditional logistics expensive actually becomes an advantage for drone networks — we can skip traffic and cross bodies of water that ground vehicles cannot.\"\n\nThe funding will also be used to grow the engineering team and develop proprietary fleet management software. The startup's technology stack is built entirely in Indonesia, a point of pride for the founding team who want to avoid dependency on foreign platforms.\n\nInvestors noted that the company's unit economics are strong, with gross margins improving each quarter as the fleet scales. Analysts expect the startup to reach profitability within 18 months if the expansion proceeds as planned.",
                'image_url'    => 'https://picsum.photos/seed/startup/800/400',
                'category_id'  => 1,
                'author'       => 'John Doe',
                'views'        => 3100,
                'published_at' => '2026-04-27 10:30:00',
            ],
            [
                'id'           => 3,
                'title'        => 'Election Results Spark National Debate',
                'slug'         => 'election-results-spark-national-debate',
                'excerpt'      => 'Analysts weigh in after yesterday\'s surprise election outcome.',
                'content'      => "Yesterday's regional election results sent shockwaves through political circles, with the incumbent coalition suffering unexpected losses in three key provinces. Political analysts are now debating what the results mean for the national political landscape ahead of the 2027 general election.\n\nThe opposition bloc, which had been largely written off in pre-election polls, managed to secure victories in areas previously considered strongholds. Exit polls suggest that economic discontent — particularly around rising food prices and unemployment among young voters — was the dominant factor driving the swing.\n\n\"This is a clear message from voters that they want accountability on economic issues,\" said Dr. Reza Hidayat, a political scientist at the University of Indonesia. \"The incumbent party needs to recalibrate its messaging and its policies if it wants to remain competitive at the national level.\"\n\nSocial media played a significant role in the campaign, with viral videos and coordinated messaging reaching millions of voters in the final days before the election. The Election Commission has called for a review of digital campaign regulations, noting that the current framework was written before platforms like TikTok existed.\n\nCountry-wide protests are expected in several cities this weekend, as supporters of both sides take to the streets. Security forces have been placed on standby, while community and religious leaders have called for calm.",
                'image_url'    => 'https://picsum.photos/seed/election/800/400',
                'category_id'  => 2,
                'author'       => 'Ahmad Rizal',
                'views'        => 8200,
                'published_at' => '2026-04-28 06:00:00',
            ],
            [
                'id'           => 4,
                'title'        => 'National Team Qualifies for World Cup',
                'slug'         => 'national-team-qualifies-world-cup',
                'excerpt'      => 'Indonesia books their spot in the 2026 World Cup finals.',
                'content'      => "After a tense 90-minute match that went to extra time, the Indonesian national football team has secured their place in the 2026 FIFA World Cup — a historic first for the country. Thousands of fans flooded the streets of Jakarta and other major cities in celebration, with the hashtag #GarudaMendunia trending globally.\n\nThe winning goal came in the 108th minute from a long-range strike by striker Marselino Ferdinan, who has been in exceptional form throughout the qualifying campaign. The goalkeeper produced multiple crucial saves in the final half-hour to preserve the lead and seal the 2-1 victory.\n\n\"I am so proud of every single player in that squad,\" said head coach Shin Tae-yong after the match. \"This team has shown incredible determination and growth over the past three years. Tonight belongs to every Indonesian.\"\n\nThe qualification has sent a wave of optimism through Indonesian football, which has long struggled to compete at the highest levels despite the country's passion for the sport. Youth academies across the archipelago have reported a surge in new registrations since the final whistle.\n\nThe Indonesian government has pledged additional investment in football infrastructure, including the construction of three new FIFA-standard stadiums. The World Cup itself will take place across multiple cities in North America, and Indonesia will enter Group D alongside Argentina, France, and Morocco.",
                'image_url'    => 'https://picsum.photos/seed/football/800/400',
                'category_id'  => 3,
                'author'       => 'Budi Santoso',
                'views'        => 12500,
                'published_at' => '2026-04-26 20:00:00',
            ],
            [
                'id'           => 5,
                'title'        => 'New Study Links Sleep to Heart Health',
                'slug'         => 'new-study-links-sleep-heart-health',
                'excerpt'      => 'Researchers find strong correlation between sleep quality and cardiovascular risk.',
                'content'      => "A landmark study published in the Journal of the American College of Cardiology has found that adults who consistently get less than six hours of sleep per night face a 34% higher risk of developing cardiovascular disease, even after controlling for other known risk factors such as smoking, obesity, and physical inactivity.\n\nThe research tracked the health outcomes of more than 50,000 participants across 12 countries over a decade. Researchers used wrist-worn devices to objectively measure sleep duration and quality, rather than relying solely on self-reported data — a significant methodological improvement over previous studies.\n\n\"What surprised us was the strength of the association even in otherwise healthy individuals,\" said lead researcher Dr. Sarah Lim. \"People who exercise regularly and eat well but consistently underslept still showed significantly elevated cardiac markers compared to those with balanced habits.\"\n\nThe study also identified fragmented sleep — waking frequently during the night — as an independent risk factor. Participants who experienced more than two significant awakenings per night had elevated levels of inflammatory markers associated with arterial plaque buildup.\n\nCardiologists have welcomed the findings and are calling for sleep quality to be incorporated into standard cardiovascular risk assessments. \"We spend enormous resources tracking cholesterol and blood pressure, but sleep barely comes up in clinical conversations,\" said Dr. Adrian Torres, a cardiologist at Singapore General Hospital. \"This study should change that.\"",
                'image_url'    => 'https://picsum.photos/seed/health/800/400',
                'category_id'  => 4,
                'author'       => 'Dr. Sarah Lim',
                'views'        => 2300,
                'published_at' => '2026-04-25 09:00:00',
            ],
            [
                'id'           => 6,
                'title'        => 'Rupiah Strengthens Against Dollar',
                'slug'         => 'rupiah-strengthens-against-dollar',
                'excerpt'      => 'Indonesia\'s currency gains ground amid positive trade data.',
                'content'      => "The Indonesian rupiah closed at its strongest level against the US dollar in eight months on Tuesday, buoyed by stronger-than-expected trade surplus data and a broadly weaker dollar following softer US inflation figures. The rupiah finished the session at Rp 15,420 per dollar, a gain of 1.2% on the day.\n\nIndonesia recorded a trade surplus of \$4.2 billion in March, well above analyst expectations of \$2.8 billion, driven by robust exports of palm oil, nickel, and coal. The data reinforced confidence in Indonesia's current account position ahead of the central bank's next policy meeting.\n\nBank Indonesia's governor welcomed the rupiah's appreciation but cautioned against excessive optimism. \"Our monetary stance remains prudent. We will continue to use available instruments to maintain stability and support growth,\" he said in a statement following the data release.\n\nForeign investors have been net buyers of Indonesian government bonds for the third consecutive month, attracted by the country's relatively high real yields compared to developed markets. Portfolio inflows have added a further tailwind to the currency.\n\nEconomists expect the rupiah to remain supported in the near term, provided global risk appetite holds steady. However, they caution that a resurgence in US inflation or a deterioration in China's economy — Indonesia's largest trading partner — could quickly reverse the trend.",
                'image_url'    => 'https://picsum.photos/seed/finance/800/400',
                'category_id'  => 5,
                'author'       => 'Eko Prasetyo',
                'views'        => 1800,
                'published_at' => '2026-04-24 14:00:00',
            ],
            [
                'id'           => 7,
                'title'        => 'Mobile App Downloads Hit Record High',
                'slug'         => 'mobile-app-downloads-record-high',
                'excerpt'      => 'Indonesia tops Southeast Asia in mobile application downloads for Q1 2026.',
                'content'      => "Indonesia has topped Southeast Asia in mobile application downloads for the first quarter of 2026, according to data released by analytics firm Sensor Tower. Indonesian users downloaded 4.8 billion apps in the three-month period, a 23% increase year-over-year, driven by strong growth in fintech, e-commerce, and short-video entertainment categories.\n\nThe numbers reflect Indonesia's rapidly growing digital economy, which is now the largest in Southeast Asia by transaction value. With more than 220 million internet users and smartphone penetration approaching 70%, Indonesia represents one of the most attractive mobile markets in the world.\n\nFintech apps saw the most dramatic growth, with digital wallet and buy-now-pay-later applications recording download increases of over 40%. Industry observers attribute this to increasing financial inclusion efforts and the expansion of merchant acceptance networks into smaller towns and rural areas.\n\n\"What's particularly exciting is the shift we're seeing from urban centers to tier-2 and tier-3 cities,\" said Renata Sari, a mobile analyst at Jakarta-based research firm Digital State. \"Apps that previously had most of their users in Jakarta and Surabaya are now seeing massive uptake in places like Palembang, Makassar, and Banjarmasin.\"\n\nLocal developers are also benefiting from the trend. Indonesian-made apps now account for 31% of the top 100 most downloaded apps in the country, up from 22% two years ago, reflecting the maturation of the local tech talent ecosystem.",
                'image_url'    => 'https://picsum.photos/seed/mobile/800/400',
                'category_id'  => 1,
                'author'       => 'Jane Smith',
                'views'        => 4100,
                'published_at' => '2026-04-23 11:00:00',
            ],
            [
                'id'           => 8,
                'title'        => 'Global Leaders Meet for Climate Summit',
                'slug'         => 'global-leaders-climate-summit',
                'excerpt'      => 'World leaders convene in Geneva to discuss new climate commitments.',
                'content'      => "Heads of state from over 80 countries gathered in Geneva this week for an emergency climate summit, convened in response to a series of unprecedented weather events that have devastated communities across three continents in the past six months. The summit was called by the United Nations Secretary-General, who described the current trajectory as \"a civilizational emergency.\"\n\nThe central debate at the summit revolves around the pace of transition away from fossil fuels and the financial commitments wealthy nations must make to support developing countries in adapting to the already-locked-in effects of climate change. A draft agreement seen by journalists proposes a \$300 billion per year climate finance package — triple the previous commitment — but disagreements remain over how much should be grants versus loans.\n\nIndonesia sent a high-level delegation led by the Minister of Environment and Forestry, who highlighted the country's significant progress in reducing deforestation rates and its ambitious plans for renewable energy expansion. Indonesia aims to achieve 34% renewable energy in its power mix by 2030, up from the current 14%.\n\nCivil society organizations staged large demonstrations outside the summit venue, calling for more ambitious commitments and legally binding targets. Many activists expressed frustration that previous agreements had not been fully implemented.\n\nThe summit is scheduled to conclude on Friday with a joint communiqué. Whether the final text will include the ambitious language demanded by small island states and climate scientists remains to be seen.",
                'image_url'    => 'https://picsum.photos/seed/climate/800/400',
                'category_id'  => 6,
                'author'       => 'John Doe',
                'views'        => 3600,
                'published_at' => '2026-04-22 07:00:00',
            ],
            [
                'id'           => 9,
                'title'        => 'Plant-Based Diet Reduces Cancer Risk by 18%',
                'slug'         => 'plant-diet-reduces-cancer-risk',
                'excerpt'      => 'A decade-long study confirms plant-based diets lower cancer incidence.',
                'content'      => "A landmark ten-year study tracking the dietary habits and health outcomes of 30,000 adults across five countries has found that individuals following a predominantly plant-based diet had an 18% lower incidence of certain cancers compared to those consuming high amounts of red and processed meat. The research, published in the British Journal of Cancer, is among the largest dietary intervention studies ever conducted.\n\nResearchers were careful to control for confounding variables including physical activity levels, smoking status, alcohol consumption, and access to healthcare. Even after adjustments, the protective effect of plant-rich diets remained statistically significant for colorectal, breast, and prostate cancers.\n\nThe study differentiated between whole-food plant-based diets — rich in vegetables, legumes, whole grains, and fruits — and highly processed vegan alternatives, finding that the former conferred greater benefits. Participants who consumed large quantities of ultra-processed plant-based products showed less pronounced improvements.\n\n\"This doesn't mean everyone needs to become vegan overnight,\" noted co-author Dr. Amelia Chandra. \"Even shifting from red meat to poultry or fish, and increasing your vegetable intake, can have measurable benefits. The key message is to eat less processed food and more whole plants.\"\n\nNutritional policy experts are calling for the findings to be incorporated into national dietary guidelines, which in many countries still recommend higher portions of animal protein than the evidence supports.",
                'image_url'    => 'https://picsum.photos/seed/diet/800/400',
                'category_id'  => 4,
                'author'       => 'Dr. Sarah Lim',
                'views'        => 5100,
                'published_at' => '2026-04-21 08:30:00',
            ],
            [
                'id'           => 10,
                'title'        => 'Tech Giant Enters Indonesian Market with $2B Investment',
                'slug'         => 'tech-giant-enters-indonesian-market',
                'excerpt'      => 'A Fortune 500 tech company announces $2B investment in Indonesia.',
                'content'      => "In what analysts are calling the largest single foreign technology investment in Indonesian history, a Fortune 500 technology company has announced a \$2 billion commitment to build data centers, expand cloud infrastructure, and train 100,000 local developers over the next five years.\n\nThe investment package includes three hyperscale data centers in West Java and Batam, which will create an estimated 5,000 direct jobs and support Indonesia's ambition to become a regional digital hub. The facilities will run on 100% renewable energy from day one, powered by a dedicated solar and geothermal supply agreement.\n\nPresident Prabowo Subianto welcomed the investment at a ceremony in Jakarta, saying it validated Indonesia's efforts to create a more competitive business environment. \"This sends a powerful message to the global investment community that Indonesia is open, stable, and ready to compete at the highest level,\" he said.\n\nLocal technology associations expressed mixed reactions. While welcoming the job creation and infrastructure development, some voices cautioned about the risks of over-reliance on foreign cloud providers for critical data. The Indonesian government's data sovereignty regulations require that data belonging to Indonesian citizens must be stored on Indonesian soil — a requirement the investment directly addresses.\n\nThe company also announced a partnership with five Indonesian universities to co-develop AI and cloud computing curricula, with a goal of producing 20,000 certified cloud professionals annually.",
                'image_url'    => 'https://picsum.photos/seed/invest/800/400',
                'category_id'  => 5,
                'author'       => 'Eko Prasetyo',
                'views'        => 7300,
                'published_at' => '2026-04-20 13:00:00',
            ],
            [
                'id'           => 11,
                'title'        => 'Quantum Computing Breakthrough Solves 100-Year-Old Math Problem',
                'slug'         => 'quantum-computing-breakthrough-math',
                'excerpt'      => 'Scientists use a quantum processor to crack a problem classical computers never could.',
                'content'      => "Researchers at a leading technology institute have demonstrated that a 127-qubit quantum processor can solve a specific class of optimization problems that would take classical supercomputers longer than the age of the universe to solve. The achievement, published in the journal Nature, represents a significant milestone in the field known as quantum advantage.\n\nThe problem in question belongs to a family of combinatorial optimization challenges that arise in logistics, drug discovery, and financial modeling. While the demonstration used a carefully constructed benchmark, scientists say it points toward near-term practical applications in molecular simulation and materials science.\n\n\"We're not claiming that quantum computers are better than classical ones for everything,\" the lead researcher said at a press conference. \"What we're showing is that there exist specific, commercially relevant problem classes where quantum processors are demonstrably superior — and that population is growing.\"\n\nThe race to quantum advantage has intensified over the past two years, with companies in the US, China, and Europe all racing to demonstrate useful quantum computations. IBM, Google, and a cluster of well-funded startups have all made significant hardware advances, while software toolkits are maturing rapidly.\n\nFor Indonesia, the development carries strategic implications. The country's National Research and Innovation Agency has recently established a quantum computing task force, with the goal of ensuring Indonesia has the human capital to participate in the quantum economy over the coming decade.",
                'image_url'    => 'https://picsum.photos/seed/quantum/800/400',
                'category_id'  => 1,
                'author'       => 'Bruce Linggard',
                'views'        => 4800,
                'published_at' => '2026-04-29 09:00:00',
            ],
            [
                'id'           => 12,
                'title'        => 'Electric Vehicle Sales Surpass Petrol Cars for First Time',
                'slug'         => 'ev-sales-surpass-petrol-cars',
                'excerpt'      => 'EV sales outpace traditional petrol vehicles in multiple Asian markets.',
                'content'      => "For the first time in automotive history, electric vehicle sales have outnumbered new petrol and diesel car registrations in three major Asian markets simultaneously — China, South Korea, and Thailand — according to the latest data from the International Energy Agency. The milestone, which analysts had predicted would not arrive until 2028, has been brought forward by falling battery costs and aggressive government incentive programs.\n\nIn China, which accounts for nearly 60% of global EV sales, the transition has been remarkable. Ten years ago, EVs represented less than 1% of new car sales. Last month, they accounted for 54%. Chinese manufacturers BYD, NIO, and Li Auto have aggressively expanded their model ranges and slashed prices, putting pressure on legacy automakers.\n\nThe Indonesian government is watching developments closely, as the country has significant nickel reserves — a key ingredient in lithium-ion batteries. Several battery gigafactories are currently under construction in Sulawesi, intended to capture more value from the country's raw material wealth rather than simply exporting unprocessed ore.\n\nHyundai's Indonesia-built Ioniq 5 has become the best-selling EV in Southeast Asia, benefiting from strong local content and a growing network of fast-charging stations. The Indonesian government's target of 2 million electric two-wheelers and 400,000 electric cars on the road by 2030 is now considered achievable by most industry analysts.",
                'image_url'    => 'https://picsum.photos/seed/ev/800/400',
                'category_id'  => 5,
                'author'       => 'Eddy McFlurry',
                'views'        => 6200,
                'published_at' => '2026-04-29 10:00:00',
            ],
            [
                'id'           => 13,
                'title'        => 'Mental Health Crisis Among Gen Z Reaches Alarming Levels',
                'slug'         => 'mental-health-crisis-gen-z',
                'excerpt'      => 'New data shows depression and anxiety rates among youth have doubled since 2019.',
                'content'      => "A comprehensive survey of mental health outcomes across 28 countries has found that rates of depression and anxiety disorders among people aged 16 to 26 have more than doubled since 2019, with the sharpest increases recorded in high-income countries with the highest rates of social media usage. The World Health Organization has described the findings as a global mental health emergency requiring immediate policy action.\n\nThe data, drawn from clinical diagnoses, self-reported surveys, and national health records, paint a consistent picture regardless of geography or economic development level. Researchers found that the strongest predictors of poor mental health outcomes were social media usage exceeding four hours per day, disrupted sleep patterns, reduced face-to-face social interaction, and perceived social comparison.\n\nIn Indonesia, the Ministry of Health has acknowledged the growing burden, noting that less than 15% of young people experiencing mental health symptoms seek professional help, largely due to stigma and limited access to services. The country has fewer than 1,000 practicing psychiatrists for a population of 280 million.\n\nSeveral technology companies have faced renewed pressure to implement stronger protections for young users following the release of the data. Proposed measures include default screen time limits for under-18 accounts, restrictions on algorithmic content amplification, and a ban on engagement-maximizing features during late-night hours.\n\nMental health advocates are calling for schools to incorporate wellbeing education into the national curriculum and for employers to offer mental health days as a standard workplace benefit.",
                'image_url'    => 'https://picsum.photos/seed/mentalhealth/800/400',
                'category_id'  => 4,
                'author'       => 'Sarah Lily',
                'views'        => 6700,
                'published_at' => '2026-04-29 08:00:00',
            ],
            [
                'id'           => 14,
                'title'        => 'Champions League Final: Real Madrid vs Manchester City',
                'slug'         => 'champions-league-final-preview',
                'excerpt'      => 'A preview of the most anticipated football match of the year.',
                'content'      => "This Saturday, Wembley Stadium will host the most anticipated club football match in a generation as Real Madrid and Manchester City meet in the UEFA Champions League Final. The fixture pits two of the greatest squads ever assembled against each other, with an estimated global television audience of 500 million tuning in.\n\nReal Madrid enter the final as slight favorites, buoyed by their extraordinary semi-final comeback against Bayern Munich, where they overturned a 3-0 deficit from the first leg to win 4-3 on aggregate. Jude Bellingham has been in unstoppable form, contributing 12 goals and 8 assists in the knockout stages alone.\n\nManchester City, under the tactical genius of Pep Guardiola, have been arguably more consistent. Their 4-1 aggregate dismantling of PSG in the semi-finals showcased the depth and fluidity of a squad that has dominated English football for half a decade. Erling Haaland has scored in every Champions League match this season — a competition record.\n\nFor Indonesian football fans, the match takes on added significance as Marselino Ferdinan — who recently signed with Manchester City after his stunning World Cup qualifying performances — is expected to start on the bench, with a possible appearance in the second half if the score allows.\n\nKick-off is scheduled for 21:00 London time on Saturday, which means Indonesian fans will be watching at 03:00 local time on Sunday. Cafes and sports bars across the country are expected to stay open for the occasion.",
                'image_url'    => 'https://picsum.photos/seed/champions/800/400',
                'category_id'  => 3,
                'author'       => 'Sam Frans',
                'views'        => 8200,
                'published_at' => '2026-04-29 07:00:00',
            ],
            [
                'id'           => 15,
                'title'        => 'Cybersecurity Threats Reach Record High in 2026',
                'slug'         => 'cybersecurity-threats-record-2026',
                'excerpt'      => 'Ransomware attacks are becoming more sophisticated and harder to detect.',
                'content'      => "The first quarter of 2026 has seen a record number of significant cyberattacks targeting critical infrastructure, healthcare systems, and financial institutions, according to the latest threat intelligence report from cybersecurity firm CrowdStrike. Ransomware incidents increased by 67% year-over-year, with average ransom demands crossing \$4 million for the first time.\n\nA new generation of ransomware groups has emerged that operates with the sophistication of a commercial software company. These groups offer \"ransomware-as-a-service\" platforms to affiliate criminals, provide 24/7 customer support, and conduct extensive reconnaissance before deploying their payloads. Several attacks in early 2026 involved months of undetected presence inside target networks before encryption was triggered.\n\nAI-generated phishing emails have dramatically increased the success rate of social engineering attacks. Security researchers report that AI-crafted emails are now virtually indistinguishable from legitimate communications and are highly personalized based on data scraped from social media and company websites.\n\nIndonesia's National Cyber and Encryption Agency reported 214 significant incidents in Q1 2026, a 45% increase from the same period last year. The banking and energy sectors were most frequently targeted. Following a major attack on a state-owned bank in February, the government has accelerated plans for a national cybersecurity operations center.\n\nExperts recommend organizations adopt a zero-trust security architecture, implement multi-factor authentication across all systems, and conduct regular red team exercises. For individuals, the advice remains consistent: use unique passwords for every account and enable two-factor authentication wherever possible.",
                'image_url'    => 'https://picsum.photos/seed/cyber/800/400',
                'category_id'  => 1,
                'author'       => 'Mike Holland',
                'views'        => 6100,
                'published_at' => '2026-04-29 11:00:00',
            ],
            [
                'id'           => 16,
                'title'        => 'Space Tourism: A Year in Review',
                'slug'         => 'space-tourism-year-review',
                'excerpt'      => 'Commercial flights to space are becoming accessible to more people.',
                'content'      => "It has been one year since SpaceX completed its first fully commercial human spaceflight mission with paying customers, and the space tourism industry is growing faster than almost anyone predicted. Over the past twelve months, six different companies have conducted crewed suborbital and orbital flights, carrying a combined total of 47 civilians to space.\n\nThe price of a suborbital experience — a 10-minute flight that takes passengers above the Kármán line and provides several minutes of weightlessness — has dropped to around \$250,000, down from \$450,000 at the start of 2025. Blue Origin's New Shepard vehicle has proved the most reliable, completing 23 consecutive successful missions.\n\nOrbital experiences remain far more expensive, with prices starting at \$10 million for a Crew Dragon seat. However, SpaceX has announced plans for a dedicated space hotel partnership that aims to bring orbital tourism within reach of high-net-worth individuals rather than exclusively billionaires.\n\nA small but growing number of Asian tourists have been among the passengers. Japan, South Korea, and China have all seen their citizens fly commercially. Indonesia has not yet been represented, though a consortium of Indonesian investors is reportedly in discussions with one provider about a dedicated Indonesian mission.\n\nCritics of the industry argue that the environmental cost of rocket launches — each of which releases significant quantities of black carbon into the upper atmosphere — is unjustifiable given the climate crisis. Defenders counter that the technology being developed will eventually have transformative benefits for humanity.",
                'image_url'    => 'https://picsum.photos/seed/space/800/400',
                'category_id'  => 1,
                'author'       => 'Chris Northen',
                'views'        => 7500,
                'published_at' => '2026-04-29 12:00:00',
            ],
            [
                'id'           => 17,
                'title'        => 'E-Commerce in Southeast Asia Hits $200 Billion',
                'slug'         => 'ecommerce-southeast-asia-200-billion',
                'excerpt'      => 'The region sees unprecedented online sales growth driven by mobile commerce.',
                'content'      => "Southeast Asia's e-commerce market has crossed the \$200 billion annual transaction value milestone, according to the latest report from Google, Temasek, and Bain & Company. The achievement came a full two years ahead of projections made in 2022, driven by accelerating smartphone adoption, improving logistics networks, and a structural shift in consumer behavior following the pandemic.\n\nIndonesia remains the region's largest single e-commerce market, accounting for approximately 45% of total transaction value. Tokopedia, Shopee, and Lazada continue to dominate, but new entrants — particularly in social commerce, where products are sold directly through social media platforms — are gaining significant ground among younger consumers.\n\nThe growth of live streaming commerce has been particularly notable. Platforms combining entertainment with shopping have generated billions of dollars in transactions, with some individual content creators selling more merchandise in a single live session than traditional retailers move in a month.\n\nLogistics infrastructure, once the biggest constraint on e-commerce growth, has improved dramatically. Same-day delivery is now available in 40 Indonesian cities, and next-day delivery covers over 90% of Java and Bali. Investment in last-mile networks in Sumatra and Kalimantan is accelerating.\n\nMicrosoft and Google are competing aggressively for the cloud infrastructure contracts that underpin these platforms, recognizing Southeast Asia as one of the fastest-growing cloud markets globally. Investment in regional data center capacity is expected to exceed \$15 billion over the next three years.",
                'image_url'    => 'https://picsum.photos/seed/ecommerce/800/400',
                'category_id'  => 5,
                'author'       => 'Eko Prasetyo',
                'views'        => 8900,
                'published_at' => '2026-04-29 13:00:00',
            ],
            [
                'id'           => 18,
                'title'        => '5G Rollout Reaches 80% of Indonesian Population',
                'slug'         => '5g-rollout-indonesia-80-percent',
                'excerpt'      => 'Ultra-fast connectivity is transforming how Indonesians work and communicate.',
                'content'      => "Indonesia's three major mobile network operators have collectively announced that 5G coverage now reaches 80% of the country's population, following an intensive 18-month infrastructure buildout that covered 50 cities and regencies across 22 provinces. The milestone makes Indonesia one of the fastest 5G deployers among emerging markets.\n\nFor most urban Indonesians, the practical impact of 5G has been immediate. Download speeds that previously averaged 40-60 Mbps on 4G now routinely exceed 400 Mbps, enabling seamless 4K video streaming, real-time cloud gaming, and near-instantaneous large file transfers.\n\nBeyond consumer applications, 5G is enabling industrial transformation. Several manufacturing facilities in Karawang and Bekasi have deployed private 5G networks to support autonomous guided vehicles, real-time quality control via machine vision, and remote operation of heavy machinery. These \"smart factory\" implementations are showing productivity gains of 15-25% in early deployments.\n\nAgriculture is another sector benefiting from connectivity improvements. In parts of Central Java, 5G-connected soil sensors and drone systems are enabling precision farming techniques that reduce water usage by 30% while increasing crop yields. The Ministry of Agriculture has launched a program to expand these pilots nationally.\n\nChallenges remain, particularly in reaching the 20% of the population — largely in rural Papua and Maluku — where 5G deployment is economically difficult. The government's Universal Service Obligation fund is being restructured to address this digital divide.",
                'image_url'    => 'https://picsum.photos/seed/5g/800/400',
                'category_id'  => 1,
                'author'       => 'Ronald Xavier',
                'views'        => 5500,
                'published_at' => '2026-04-29 14:00:00',
            ],
            [
                'id'           => 19,
                'title'        => 'Indonesia Wins First Olympic Gold in Athletics',
                'slug'         => 'indonesia-first-olympic-gold-athletics',
                'excerpt'      => 'History made at the 2026 Asian Athletics Championship in Surabaya.',
                'content'      => "In a moment that will be replayed on Indonesian television for decades, sprinter Lalu Muhammad Zohri crossed the finish line of the 100-meter final at the Asian Athletics Championship in Surabaya to take gold — setting a new Asian record of 9.81 seconds in the process. The crowd of 40,000 at Gelora Delta Sidoarjo erupted in scenes of pure joy.\n\nZohri, who first captured national attention as a teenager with his World Junior Championship title, has spent the past four years under a specialist sprint coach in the United States. The investment in elite-level foreign coaching has clearly paid dividends, with the 25-year-old now comfortably among the top 10 sprinters in the world.\n\n\"I ran for every Indonesian today,\" Zohri said through tears at the post-race ceremony. \"Every child who watches this and thinks they can be a champion — I want them to know they can.\"\n\nThe achievement comes at a significant moment for Indonesian athletics. The country is preparing to host a major multi-sport event in 2028 and has been under pressure to develop elite athletic programs rather than relying on the traditional strengths of badminton and weightlifting.\n\nThe Indonesian Ministry of Youth and Sport has announced that a new high-performance athletics training center will be constructed in East Java, with a target of producing five internationally competitive sprinters within a decade.",
                'image_url'    => 'https://picsum.photos/seed/athletics/800/400',
                'category_id'  => 3,
                'author'       => 'Budi Santoso',
                'views'        => 11200,
                'published_at' => '2026-04-28 18:00:00',
            ],
            [
                'id'           => 20,
                'title'        => 'Breakthrough in Cancer Immunotherapy Doubles Survival Rates',
                'slug'         => 'cancer-immunotherapy-breakthrough',
                'excerpt'      => 'A new targeted therapy shows promising results in clinical trials.',
                'content'      => "A new form of cancer immunotherapy using genetically engineered T-cells has shown remarkable efficacy in a Phase 3 clinical trial, more than doubling five-year survival rates for patients with late-stage colorectal cancer compared to standard chemotherapy. The results, announced at the American Society of Clinical Oncology annual meeting, represent what many experts are calling the most significant advance in oncology in a decade.\n\nThe therapy, known as CAR-T cell treatment, involves extracting a patient's own immune cells, genetically reprogramming them in a laboratory to recognize and attack cancer cells, and then reinfusing them. Previous CAR-T therapies have been effective against blood cancers, but this is the first to demonstrate strong efficacy against a solid tumor.\n\nThe trial enrolled 847 patients across 14 countries. Patients receiving the new therapy had a median progression-free survival of 31 months, compared to 14 months for those receiving standard treatment. Side effects, while present, were manageable in most cases.\n\nAccessibility remains a significant challenge. Current manufacturing costs for personalized CAR-T therapies run to hundreds of thousands of dollars per patient. Researchers are working on \"off-the-shelf\" versions using donor cells that could dramatically reduce costs, but these have shown lower efficacy in early trials.\n\nIn Indonesia, the National Cancer Center has begun the process of licensing the technology, with a goal of making the therapy available to patients within three years. The government is in discussions with the drug developer about differential pricing for lower-income markets.",
                'image_url'    => 'https://picsum.photos/seed/cancer/800/400',
                'category_id'  => 4,
                'author'       => 'Dr. Sarah Lim',
                'views'        => 9800,
                'published_at' => '2026-04-29 06:00:00',
            ],
            [
                'id'           => 21,
                'title'        => 'New Trade Agreement Opens Doors for ASEAN Businesses',
                'slug'         => 'asean-trade-agreement-2026',
                'excerpt'      => 'ASEAN nations sign landmark trade deal to boost intra-regional commerce.',
                'content'      => "The ten member states of the Association of Southeast Asian Nations signed a landmark trade facilitation agreement in Kuala Lumpur, pledging to eliminate tariffs on 95% of goods traded between them by 2028 and to standardize customs procedures to reduce border crossing times from an average of 48 hours to under 4 hours.\n\nThe agreement, which took three years to negotiate, is expected to add \$180 billion to regional GDP over five years, according to the Asian Development Bank. Small and medium enterprises, which currently struggle with complex documentation requirements when trading across ASEAN borders, are expected to be the primary beneficiaries.\n\nFor Indonesia, the deal opens significant new opportunities in food processing, textiles, and digital services. The country's Minister of Trade described it as \"a generational opportunity\" to integrate Indonesian businesses into regional value chains.\n\nOne contentious provision allows digital services companies to operate across borders under a single license issued by any ASEAN member state — a measure that has delighted the technology industry but concerned some policymakers who worry about regulatory arbitrage.\n\nImplementation will require significant domestic reform in several countries, including modernizing customs information systems and training border officials. The ADB has provided a \$2 billion loan facility to support member states in making the necessary infrastructure investments.",
                'image_url'    => 'https://picsum.photos/seed/trade/800/400',
                'category_id'  => 5,
                'author'       => 'Sammy Harris',
                'views'        => 5800,
                'published_at' => '2026-04-28 12:00:00',
            ],
            [
                'id'           => 22,
                'title'        => 'Mindfulness at Work: Companies See 25% Productivity Gain',
                'slug'         => 'mindfulness-work-productivity-study',
                'excerpt'      => 'Corporations that implement structured mindfulness programs report significant gains.',
                'content'      => "A two-year study tracking 3,200 employees at 40 companies across eight industries has found that structured workplace mindfulness programs — including guided meditation sessions, mindful communication training, and dedicated focus time — are associated with a 25% improvement in self-reported productivity, a 31% reduction in absenteeism, and significantly lower employee turnover.\n\nThe research, conducted by the Harvard Business School in partnership with several major corporations, controlled for industry, company size, and pre-existing wellness culture. The effect sizes were consistent across demographic groups, though younger employees and those in high-stress roles showed the largest improvements.\n\nNot all mindfulness interventions were equally effective. Brief \"mindfulness washes\" — optional five-minute sessions added to the end of meetings — showed minimal benefit. The programs that worked best were integrated into the workday structure, had visible senior leadership participation, and were combined with systemic changes such as meeting-free afternoons and clear boundaries around after-hours communication.\n\n\"This isn't about asking people to meditate and then sending them back into a dysfunctional environment,\" said the study's lead author. \"The organizations that saw the biggest gains used mindfulness as a gateway to rethinking how work happens, not just as a stress management tool.\"\n\nSeveral Indonesian conglomerates and multinationals have already begun piloting programs based on the study's methodology, with early results expected to be published later this year.",
                'image_url'    => 'https://picsum.photos/seed/mindful/800/400',
                'category_id'  => 4,
                'author'       => 'Tom Middleton',
                'views'        => 2900,
                'published_at' => '2026-04-28 10:00:00',
            ],
            [
                'id'           => 23,
                'title'        => 'Women\'s World Cup: Host Nation Indonesia Makes History',
                'slug'         => 'womens-world-cup-indonesia-history',
                'excerpt'      => 'Indonesia\'s women\'s team qualifies for the knockout stage for the first time.',
                'content'      => "The Indonesian women's national football team has achieved the unthinkable, becoming the first host nation in the history of the Women's World Cup to qualify for the knockout stage on debut. A hard-fought 1-0 victory over Denmark in their final group stage match, secured by a stunning 87th-minute header from captain Siti Rahayu, confirmed Indonesia's place in the Round of 16.\n\nThe result was met with scenes of extraordinary jubilation across the archipelago. In Jakarta alone, an estimated 150,000 people gathered in public spaces to watch the final minutes of the match on giant screens, with the country coming to a virtual standstill during the final 15 minutes.\n\nThe team's success has been built over four years of intensive development following Indonesia's successful bid to host the tournament. The Football Association of Indonesia partnered with the Dutch FA to provide coaching expertise, and 23 of the 26-woman squad now play professionally in Europe or Australia.\n\n\"When we were given this opportunity to host the World Cup, we made a promise that the Indonesian team would make their country proud,\" said coach Vera Pauw. \"These players have worked harder than any group I have ever worked with. They deserve every moment of what they're experiencing.\"\n\nIndonesia will face Spain in the Round of 16, a match that will be played on Thursday at Gelora Bung Karno in Jakarta. Ticket demand has been overwhelming, with the stadium's 77,000-capacity expected to sell out within minutes when additional allocation is released tomorrow.",
                'image_url'    => 'https://picsum.photos/seed/womensfootball/800/400',
                'category_id'  => 3,
                'author'       => 'Zein Larry',
                'views'        => 9100,
                'published_at' => '2026-04-30 06:00:00',
            ],
            [
                'id'           => 24,
                'title'        => 'Ocean Plastics: New Biodegradable Alternative Passes Final Tests',
                'slug'         => 'biodegradable-plastic-ocean-solution',
                'excerpt'      => 'Scientists develop a fully marine-degradable plastic replacement.',
                'content'      => "A research consortium led by scientists at the Bandung Institute of Technology and Stanford University has successfully completed field trials of a novel biopolymer material that degrades completely in seawater within six months without releasing microplastics or toxic compounds. The material, derived from seaweed and cassava starch, can be manufactured at roughly 1.5 times the cost of conventional single-use plastic — a premium that packaging industry analysts say will fall below parity within three years as production scales.\n\nThe Indonesian researchers played a central role in developing the material, motivated by Indonesia's status as the world's second-largest contributor to ocean plastic pollution. The Jawa Sea and Makassar Strait are among the most plastic-contaminated waterways globally, with significant damage to coral reefs and fisheries.\n\n\"We have a responsibility because of our geography and our history with plastic waste, but we also have incredible natural resources — our seaweed industry is the world's second largest — that give us an advantage in developing solutions,\" said the project's principal investigator, Professor Andi Kurniawan.\n\nSeveral Indonesian consumer goods companies have already signed letters of intent to pilot the material in their packaging lines. The government has introduced a regulatory fast track for sustainable packaging innovations, allowing compliant products to bypass certain import and safety approval timelines.\n\nEnvironmentalists have cautiously welcomed the development but note that even biodegradable materials are inferior to reduced consumption and robust waste management systems. \"This is a useful tool, not a silver bullet,\" said a spokesperson for the Coral Triangle Initiative.",
                'image_url'    => 'https://picsum.photos/seed/ocean/800/400',
                'category_id'  => 6,
                'author'       => 'Evan Harris',
                'views'        => 4400,
                'published_at' => '2026-04-30 07:00:00',
            ],
            [
                'id'           => 25,
                'title'        => 'Renewable Energy Hits 40% of Indonesia Power Grid',
                'slug'         => 'renewable-energy-40-percent-indonesia',
                'excerpt'      => 'Next-generation solar and geothermal plants power a greener future.',
                'content'      => "Indonesia has achieved a major milestone in its energy transition, with renewable sources now accounting for 40% of total electricity generation capacity — a figure that exceeded the government's original 2026 target of 34%. The achievement reflects accelerating investment in geothermal, solar, and hydroelectric generation over the past four years.\n\nGeothermal energy, for which Indonesia has the world's largest resource potential, continues to be the cornerstone of the transition. Seven new geothermal plants came online in 2025 across Java, Sulawesi, and North Sumatra, adding 1,200 megawatts of reliable baseload capacity. Unlike solar and wind, geothermal provides 24-hour generation that does not require battery storage.\n\nSolar installations have also surged, with the cost of utility-scale solar in Indonesia falling to \$0.028 per kilowatt-hour — comparable to the cheapest coal generation. A cluster of large solar parks in the arid regions of East Nusa Tenggara and East Java are expected to add 3,500 MW of capacity by end of year.\n\nThe state electricity company PLN has invested heavily in grid modernization to handle the variability of renewable generation, including advanced energy management systems and expanded interconnection between islands. Battery storage installations are growing rapidly, though the high capital cost remains a constraint.\n\nThe transition has created over 180,000 jobs in renewable energy construction, manufacturing, and operations — partially offsetting the decline in coal-related employment in regions like South Kalimantan and East Kalimantan.",
                'image_url'    => 'https://picsum.photos/seed/tech/800/400',
                'category_id'  => 6,
                'author'       => 'Silver Roger',
                'views'        => 4914,
                'published_at' => '2026-04-30 08:00:00',
            ],
            [
                'id'           => 26,
                'title'        => 'Political Reform Bill Passes Despite Opposition',
                'slug'         => 'political-reform-bill-passes',
                'excerpt'      => 'Parliament approves sweeping changes to campaign finance laws.',
                'content'      => "Indonesia's parliament voted 362 to 199 to pass the most significant campaign finance reform in the country's democratic history, introducing strict limits on political donations, mandatory real-time disclosure of campaign expenditure, and a new independent electoral audit body with prosecutorial powers.\n\nThe bill, which had been the subject of intense lobbying from both business groups and civil society organizations, passed after a marathon 14-hour parliamentary session that extended into the early hours of the morning. Thirteen members of the ruling coalition crossed the floor to vote with the opposition in support of the reforms.\n\nKey provisions include a cap on individual donations to political parties of Rp 500 million per year, a ban on corporate donations above Rp 2 billion, and a requirement for all campaign expenditure above Rp 10 million to be reported to the new audit body within 48 hours. Violations carry penalties of up to 10 years imprisonment.\n\nTransparency International Indonesia hailed the vote as \"a watershed moment,\" while noting that the true test will be in enforcement. Previous campaign finance regulations have been largely ignored due to weak oversight mechanisms.\n\nThe opposition, which supports the reforms in principle, voted against several procedural aspects of the bill's passage, arguing that insufficient time was provided for public consultation. They have indicated they will challenge specific provisions in the Constitutional Court.",
                'image_url'    => 'https://picsum.photos/seed/summit/800/400',
                'category_id'  => 2,
                'author'       => 'George Bringham',
                'views'        => 3800,
                'published_at' => '2026-04-30 09:00:00',
            ],
            [
                'id'           => 27,
                'title'        => 'Startup Ecosystem Report: Jakarta Enters Top 20 Global Hubs',
                'slug'         => 'jakarta-top-20-startup-hub',
                'excerpt'      => 'Innovation is thriving as Jakarta climbs the global startup ranking.',
                'content'      => "Jakarta has entered the top 20 global startup ecosystems for the first time, according to the annual Startup Genome Global Ecosystem Report. The Indonesian capital ranked 18th globally, up seven places from last year, with particular strength in fintech, health tech, and climate tech verticals.\n\nThe report highlights several factors driving Jakarta's rise: a large and digitally engaged consumer population, growing availability of early-stage capital from local venture funds, an emerging pool of serial entrepreneurs who have successfully exited previous ventures, and improving government support through regulatory sandboxes and startup visa programs.\n\nThe city is home to four unicorns — private companies valued at over \$1 billion — with three more expected to reach that milestone within the next 18 months based on recent funding rounds. The total value of Jakarta-based startups in the private market now exceeds \$45 billion.\n\nChallenges remain, particularly around access to technical talent. Despite producing 200,000 STEM graduates annually, demand from startups, established technology companies, and government digital transformation programs significantly exceeds supply. Bootcamp and accelerator programs are helping bridge the gap, but industry leaders say the structural solution requires curriculum reform at the university level.\n\nInternational investors are taking notice. Silicon Valley funds including Sequoia Capital and Andreessen Horowitz have recently opened Jakarta offices, and deals between Indonesian startups and Southeast Asian counterparts are becoming increasingly common.",
                'image_url'    => 'https://picsum.photos/seed/emerging/800/400',
                'category_id'  => 5,
                'author'       => 'Shanks Walkman',
                'views'        => 6408,
                'published_at' => '2026-04-30 10:00:00',
            ],
            [
                'id'           => 28,
                'title'        => 'Nutritional Science Upends Decades of Dietary Advice',
                'slug'         => 'nutritional-science-new-findings',
                'excerpt'      => 'New findings challenge long-held beliefs about fat, carbs, and protein.',
                'content'      => "A series of landmark studies published simultaneously in three leading medical journals has overturned several widely held beliefs about dietary fat, carbohydrates, and their relationship to cardiovascular disease and metabolic health. The research represents the culmination of a decade of large-scale, rigorously controlled nutritional epidemiology.\n\nPerhaps most controversially, the studies found that dietary saturated fat — long demonized as the primary driver of heart disease — has a more nuanced relationship with cardiovascular outcomes than previously understood. The risk associated with saturated fat appears to depend heavily on the food matrix in which it is consumed and on what replaces it in the diet. Replacing saturated fat with refined carbohydrates, as public health campaigns encouraged in the 1980s and 1990s, appears to have been actively harmful.\n\nThe research also significantly rehabilitates the role of dietary fat in metabolic health. Participants following a diet rich in whole-food fats — avocado, nuts, olive oil, and fatty fish — showed better insulin sensitivity, lower triglycerides, and smaller waist circumference than those following low-fat dietary guidelines.\n\n\"We are not saying fat is fine and carbs are the enemy,\" said the coordinating researcher. \"We are saying that quality matters more than macronutrient ratios, and that decades of focusing on single nutrients rather than whole dietary patterns has led us astray.\"\n\nIndonesian nutritionists have welcomed the findings, noting that traditional Indonesian diets — rich in tempeh, fish, vegetables, and coconut — appear vindicated by the new evidence, and that the country's shift toward ultra-processed Western food imports is the real nutritional concern.",
                'image_url'    => 'https://picsum.photos/seed/nutrition/800/400',
                'category_id'  => 4,
                'author'       => 'Van Louis',
                'views'        => 5200,
                'published_at' => '2026-04-30 11:00:00',
            ],
            [
                'id'           => 29,
                'title'        => 'Global Cybercrime Treaty Signed by 130 Nations',
                'slug'         => 'global-cybercrime-treaty-130-nations',
                'excerpt'      => 'Historic agreement creates a framework for cross-border cybercrime prosecution.',
                'content'      => "Representatives from 130 countries signed the United Nations Convention against Cybercrime in Vienna, creating for the first time a binding international legal framework for investigating and prosecuting cybercriminal activity that crosses national borders. The treaty, which took six years to negotiate, will enter into force once ratified by 40 signatory states.\n\nThe convention establishes common definitions for cybercrime offenses including unauthorized access, data theft, ransomware, and child sexual exploitation material online. It creates mutual legal assistance obligations, allowing countries to request evidence and cooperation from fellow signatories without going through slow diplomatic channels.\n\nHuman rights organizations have raised concerns about several provisions that they say could be used by authoritarian governments to prosecute legitimate political dissent and investigative journalism conducted online. The convention's definition of cybercrime is broad enough to potentially criminalize activities that are legal or protected under international human rights law in many countries.\n\nIndonesia signed the treaty and has committed to ratifying it within 18 months. The Ministry of Communication and Information Technology has noted that the framework will help Indonesian authorities pursue criminal groups that operate ransomware and fraud operations from overseas.\n\nThe convention is seen as particularly important for combating the rapidly growing problem of cyber-enabled financial fraud, which the World Bank estimates costs the global economy \$600 billion annually — a figure that has tripled in five years.",
                'image_url'    => 'https://picsum.photos/seed/cyber2/800/400',
                'category_id'  => 6,
                'author'       => 'Evan Harris',
                'views'        => 4200,
                'published_at' => '2026-04-30 12:00:00',
            ],
            [
                'id'           => 30,
                'title'        => 'Indonesia Passes Comprehensive Data Privacy Law',
                'slug'         => 'indonesia-data-privacy-law-2026',
                'excerpt'      => 'New legislation gives Indonesians control over their personal data.',
                'content'      => "After three years of debate and revisions, Indonesia's Parliament has passed a comprehensive Personal Data Protection Law that gives citizens meaningful control over how their data is collected, processed, and shared by both government agencies and private companies. The law takes effect immediately for large enterprises and will apply to all organizations within 24 months.\n\nThe legislation, widely compared to Europe's GDPR in scope and intent, requires organizations to obtain explicit consent before collecting personal data, to disclose what data is held and why, to allow individuals to access and delete their data, and to report data breaches to authorities and affected individuals within 72 hours of discovery.\n\nFines for violations can reach 2% of annual revenue for organizations that process data without adequate legal basis, and up to 4% for the most serious violations including unlawful transfer of data overseas. A new Data Protection Authority has been established with a budget of Rp 500 billion and powers to investigate, audit, and sanction.\n\nThe technology industry has broadly welcomed the regulatory clarity, noting that operating across multiple jurisdictions with inconsistent rules has been burdensome. Several multinational companies have already begun aligning their Indonesian operations with the new requirements in advance of formal enforcement.\n\nConsumer advocacy groups praised the law's passage but noted several areas where they consider the protections weaker than the European standard, including provisions allowing the government to access personal data for national security purposes without judicial oversight.",
                'image_url'    => 'https://picsum.photos/seed/privacy/800/400',
                'category_id'  => 2,
                'author'       => 'Ahmad Rizal',
                'views'        => 6300,
                'published_at' => '2026-04-30 13:00:00',
            ],
        ];

        $rows = [];
        foreach ($articles as $article) {
            $rows[] = array_merge($article, ['created_at' => now(), 'updated_at' => now()]);
        }
        DB::table('articles')->insert($rows);

        DB::table('article_tags')->insert([
            ['article_id' => 1,  'tag_id' => 1],  ['article_id' => 1,  'tag_id' => 2],
            ['article_id' => 2,  'tag_id' => 2],  ['article_id' => 2,  'tag_id' => 4],
            ['article_id' => 3,  'tag_id' => 5],
            ['article_id' => 4,  'tag_id' => 6],
            ['article_id' => 5,  'tag_id' => 7],
            ['article_id' => 6,  'tag_id' => 8],  ['article_id' => 6,  'tag_id' => 4],
            ['article_id' => 7,  'tag_id' => 3],
            ['article_id' => 8,  'tag_id' => 9],
            ['article_id' => 9,  'tag_id' => 7],
            ['article_id' => 10, 'tag_id' => 1],  ['article_id' => 10, 'tag_id' => 8],
            ['article_id' => 11, 'tag_id' => 1],
            ['article_id' => 12, 'tag_id' => 4],  ['article_id' => 12, 'tag_id' => 8],
            ['article_id' => 13, 'tag_id' => 7],
            ['article_id' => 14, 'tag_id' => 6],
            ['article_id' => 15, 'tag_id' => 10],
            ['article_id' => 16, 'tag_id' => 1],
            ['article_id' => 17, 'tag_id' => 4],  ['article_id' => 17, 'tag_id' => 3],
            ['article_id' => 18, 'tag_id' => 3],
            ['article_id' => 19, 'tag_id' => 6],
            ['article_id' => 20, 'tag_id' => 7],
            ['article_id' => 21, 'tag_id' => 4],  ['article_id' => 21, 'tag_id' => 8],
            ['article_id' => 22, 'tag_id' => 7],
            ['article_id' => 23, 'tag_id' => 6],
            ['article_id' => 24, 'tag_id' => 9],
            ['article_id' => 25, 'tag_id' => 9],  ['article_id' => 25, 'tag_id' => 4],
            ['article_id' => 26, 'tag_id' => 5],
            ['article_id' => 27, 'tag_id' => 2],  ['article_id' => 27, 'tag_id' => 8],
            ['article_id' => 28, 'tag_id' => 7],
            ['article_id' => 29, 'tag_id' => 10],
            ['article_id' => 30, 'tag_id' => 10], ['article_id' => 30, 'tag_id' => 5],
        ]);

        DB::table('bookmarks')->insert([
            ['user_id' => 1, 'article_id' => 1,  'created_at' => now(), 'updated_at' => now()],
            ['user_id' => 1, 'article_id' => 4,  'created_at' => now(), 'updated_at' => now()],
            ['user_id' => 1, 'article_id' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['user_id' => 2, 'article_id' => 3,  'created_at' => now(), 'updated_at' => now()],
            ['user_id' => 2, 'article_id' => 20, 'created_at' => now(), 'updated_at' => now()],
        ]);

        DB::table('user_category_preferences')->insert([
            ['user_id' => 1, 'category_id' => 1],
            ['user_id' => 1, 'category_id' => 3],
            ['user_id' => 2, 'category_id' => 2],
            ['user_id' => 2, 'category_id' => 5],
        ]);
    }
}
